Households aware of heat pumps and consider them for emergency breakdowns if boiler ban active
centrefornetzero/domestic-heating-abm pull request #58
Opened 2022-01-17 12:59 UTC by stephanie-chan-cnz

2022-01-17 14:10 UTC, tomwphillips requested changes
I'm not keen on changing `is_heat_pump_aware` to `is_heat_pump_aware_init`. 

I think the logic you've put in the new function `is_heat_pump_aware` is in the wrong place. Instead I think you should put it in `get_heating_system_options`, which gets `model` and can therefore find out if there is a ban or not. That function can then decide whether to use the `is_heat_pump_aware` attribute.

Then you could leave `is_heat_pump_aware` as an attribute set at `__init__`.

2022-01-17 14:11 UTC, tomwphillips commented
The failing test is also failing on main so I don't think it's anything to do with your branch. I'm looking into the failure now.

2022-01-17 14:20 UTC, stephanie-chan-cnz commented
> I'm not keen on changing `is_heat_pump_aware` to `is_heat_pump_aware_init`.
> 
> I think the logic you've put in the new function `is_heat_pump_aware` is in the wrong place. Instead I think you should put it in `get_heating_system_options`, which gets `model` and can therefore find out if there is a ban or not. That function can then decide whether to use the `is_heat_pump_aware` attribute.
> 
> Then you could leave `is_heat_pump_aware` as an attribute set at `__init__`.

OK, I had first thought about implementing it this way, but decided it preferable to actually update the underlying household attribute the logic is referencing - awareness. I don't mind.

2022-01-19 15:46 UTC, tomwphillips approved these changes

2022-01-19 15:50 UTC, merged